// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.



// var CACHE_NAME = 'site-entry-cache-v1';
// var urlsToCache = [
// 	'./index.html',
// 	'./portal/feature/auth/portal.auth.component.html',
// 	'./portal/feature/auth/portal.auth.component.css',
// 	'./app/idv/idv.component.html',
// 	'./app/idv/idv.component.css'
// ];

// self.addEventListener('install', function (event) {
// 	console.log('[ServiceWorker] Install');
// 	event.waitUntil(
// 		caches.open(CACHE_NAME)
// 		.then( function (cache) {
// 			console.log('[ServiceWorker] Caching app shell');
// 			return cache.addAll(urlsToCache);
// 		})
// 	);
// });
// 

console.log('[service-worker accessed!]')
